<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE credits_data [
<!ELEMENT credits_data (credits, assets, licenses, others)>
<!ELEMENT credits (credit)*>
<!ELEMENT credit (#PCDATA)>
<!ELEMENT assets (asset)*>
<!ELEMENT asset (assetname, author, from, license, extra?)>
<!ELEMENT assetname (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT from (#PCDATA)>
<!ELEMENT license (#PCDATA)>
<!ELEMENT extra (#PCDATA)>
<!ELEMENT licenses (licensetext)*>
<!ELEMENT licensetext (#PCDATA)>
<!ELEMENT others (other)*>
<!ELEMENT other (#PCDATA)>
]>
<credits_data>
<!--
TextMeshPro newline: &lt;br&gt;
turns into <br> when read
-->
<credits>
<credit>
This game was developed by 11BelowStudio
for the So Bad It's Good Jam 2022
</credit>
</credits>
<assets>
<!--

For all the assets obtained from elsewhere:
Add the info about the asset name, who it's by,
where it's from, and what license it was distributed under
in here, within a '<asset>' element.


For example:

<asset>
<assetname>haha 'ass'et lmao</assetname>
<author>Joe Momma</author>
<from>https://en.wikipedia.org/wiki/Special:Random</from>
<license>MIT license</license>
<extra>An optional bit of supplementary data because reasons I guess :shrug:</extra>
</asset>
-->
<asset>
<assetname>Tortoise - Turtle</assetname>
<author>Daniel Zuleta Art</author>
<from>https://sketchfab.com/3d-models/ 
tortoise-turtle-031b140380654dedb3b18e7cdd8c190c</from>
<license>CC-BY-4.0</license>
</asset>
<asset>
<assetname>Comic Neue (font)</assetname>
<author>Craig Rozynski et al</author>
<from>http://comicneue.com/</from>
<license>Open Font License v1.1</license>
</asset>
<asset>
<assetname>Olde English Regular (font)</assetname>
<author>Dieter Steffmann</author>
<from>https://www.fontspace.com/olde-english-font-f37119</from>
<license>Freeware</license>
</asset>
<asset>
<assetname>Dead Turtle Table</assetname>
<author>Duznot</author>
<from>https://sketchfab.com/3d-models/
dead-turtle-table-854313a3ea1d4e6184b33e4b91b333e9</from>
<license>CC-BY-4.0</license>
</asset>
<asset>
<assetname>Testudo</assetname>
<author>???</author>
<from>https://pnghut.com/png/ZHHUsNZAz4/</from>
<license>???</license>
</asset>
    <asset>
        <assetname>DevTex: Prototyping Textures</assetname>
        <author>GIB Games</author>
        <from>https://assetstore.unity.com/packages/2d/textures-materials/
devtex-prototyping-textures-176107</from>
        <license>Standard Unity Asset Store EULA</license>
    </asset>
    <asset>
        <assetname>Snaps Prototype | Office</assetname>
        <author>Unity Technologies</author>
        <from>https://assetstore.unity.com/packages/3d/environments/
snaps-prototype-office-137490</from>
        <license>Standard Unity Asset Store EULA</license>
    </asset>
    <asset>
        <assetname>Snaps Prototype | Sci-Fi / Industrial</assetname>
        <author>Unity Technologies</author>
        <from>https://assetstore.unity.com/packages/3d/environments/
sci-fi/snaps-prototype-sci-fi-industrial-136759</from>
        <license>Standard Unity Asset Store EULA</license>
    </asset>
    <asset>
        <assetname>Pillow</assetname>
        <author>khanhnguyen1189</author>
        <from>https://sketchfab.com/3d-models/
pillow-ffedc1b62f8d485bb19392c6d33fb71d</from>
        <license>CC-BY-4.0</license>
    </asset>
    <asset>
        <assetname>[FREE] Ancient Rome Trap Beat - Julius Caesar Type Beat *HARD*</assetname>
        <author>prod. Stefan</author>
        <from>https://www.youtube.com/watch?v=fsZic5DCRUk</from>
        <license>Non-profit use with attribution is allowed</license>
    </asset>
    <asset>
        <assetname>roomtone</assetname>
        <author>Mydo1</author>
        <from>https://freesound.org/people/Mydo1/sounds/198957/</from>
        <license>CC-0 (public domain)</license>
    </asset>
    <asset>
        <assetname>Plate Armor- Rustle 3</assetname>
        <author>Samulis</author>
        <from>https://freesound.org/people/Samulis/sounds/209400/</from>
        <license>CC-BY-3.0</license>
    </asset>
    <asset>
        <assetname>Carefree</assetname>
        <author>Kevin MacLeod (Incompetech.com)</author>
        <from>https://incompetech.com/music/royalty-free/music.html</from>
        <license>CC-BY-4.0</license>
    </asset>
</assets>
<licenses>
<!--
<licensetext>
words words words
</licensetext>
-->
<!--
For some licenses (such as the MIT license), there is a legal requirement
to include a copy of some of the license text in anything that uses the
code released under that license. So, for those sorts of licenses,
copy the legally mandatory text into a 'licensetext' element down here, as follows:

<licensetext>
Copyright © 2022 Joe Mamma

Permission is hereby granted, free of charge, to any person obtaining a
copy of this software and associated documentation files (the “Software”),
to deal in the Software without restriction, including without limitation
the rights to use, copy, modify, merge, publish, distribute, sublicense,
and/or sell copies of the Software, and to permit persons to whom the Software
is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included
in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
</licensetext>
-->
</licenses>
<others>
<!--
For other bits of credits that don't neatly fit in elsewhere.
-->
<other>
Developed using Unity 2020.3.37f1
</other>
<other>
Featuring Tortelvis as himself
(via a few samples from Dread Zeppelin - Black Dog and Dread Zeppelin - Stir It Up)
</other>
<other>
This is totally not a ripoff of One Night At Flumpty's 2. no bamboozle.
</other>
<other>
This game was made entirely during the weekend of the 6th-7th of august,
and the cheap energy drinks at tesco are surprisingly potent.
</other>
<other>
Somehow, this game came in 9th place overall during the 2022 So Bad It's Good Jam (and #1 for the 'modifier' category)!
Special thanks to everyone else who participated in the So Bad It's Good Jam, for giving me a reason to make this game, giving me some feedback on it, and generally putting up with my presence
</other>
</others>
</credits_data>